"""Remove foreign keys and update relationships

Revision ID: 4779c4b3a4f4
Revises: 75df4a590fb2
Create Date: 2026-01-01 00:41:32.930022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4779c4b3a4f4'
down_revision = '75df4a590fb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints by finding them dynamically
    from sqlalchemy import inspect
    
    def drop_all_foreign_keys(table_name):
        """Drop all foreign key constraints from a table"""
        conn = op.get_bind()
        inspector = inspect(conn)
        fks = inspector.get_foreign_keys(table_name)
        for fk in fks:
            op.drop_constraint(fk['name'], table_name, type_='foreignkey')
    
    # Drop foreign keys from images table
    drop_all_foreign_keys('images')
    
    # Add index and drop foreign key from orders table
    op.create_index(op.f('ix_orders_plan_id'), 'orders', ['plan_id'], unique=False)
    drop_all_foreign_keys('orders')
    
    # Add indexes and drop foreign keys from process_tasks table
    op.create_index(op.f('ix_process_tasks_image_id'), 'process_tasks', ['image_id'], unique=False)
    op.create_index(op.f('ix_process_tasks_result_image_id'), 'process_tasks', ['result_image_id'], unique=False)
    drop_all_foreign_keys('process_tasks')
    
    # Drop foreign key from quiz_sessions table
    drop_all_foreign_keys('quiz_sessions')
    
    # Add index and drop foreign key from subscriptions table
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    drop_all_foreign_keys('subscriptions')
    
    # Add index and drop foreign keys from works table
    op.create_index(op.f('ix_works_processed_image_id'), 'works', ['processed_image_id'], unique=False)
    drop_all_foreign_keys('works')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('works_ibfk_1'), 'works', 'images', ['processed_image_id'], ['id'])
    op.create_foreign_key(op.f('works_ibfk_2'), 'works', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_works_processed_image_id'), table_name='works')
    op.create_foreign_key(op.f('subscriptions_ibfk_1'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.create_foreign_key(op.f('quiz_sessions_ibfk_1'), 'quiz_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('process_tasks_ibfk_2'), 'process_tasks', 'images', ['result_image_id'], ['id'])
    op.create_foreign_key(op.f('process_tasks_ibfk_1'), 'process_tasks', 'images', ['image_id'], ['id'])
    op.create_foreign_key(op.f('process_tasks_ibfk_3'), 'process_tasks', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_process_tasks_result_image_id'), table_name='process_tasks')
    op.drop_index(op.f('ix_process_tasks_image_id'), table_name='process_tasks')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_plan_id'), table_name='orders')
    op.create_foreign_key(op.f('images_ibfk_1'), 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

