"""Initial migration

Revision ID: 75df4a590fb2
Revises: 
Create Date: 2026-01-01 00:20:04.350387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75df4a590fb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Enum('MONTHLY', 'ANNUAL', name='planid'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_subtext', sa.String(length=100), nullable=True),
    sa.Column('badge_text', sa.String(length=50), nullable=True),
    sa.Column('badge_color', sa.String(length=20), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('highlighted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_pro', sa.Boolean(), nullable=True),
    sa.Column('membership_type', sa.Enum('FREE', 'MONTHLY', 'ANNUAL', 'ENTERPRISE', name='membershiptype'), nullable=True),
    sa.Column('membership_expiry', sa.DateTime(), nullable=True),
    sa.Column('wechat_openid', sa.String(length=100), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.create_table('verification_codes',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_codes_phone_number'), 'verification_codes', ['phone_number'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('JPG', 'PNG', 'WEBP', name='imageformat'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_user_id'), 'images', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.Enum('MONTHLY', 'ANNUAL', name='planid'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('WECHAT', 'ALIPAY', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'EXPIRED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('payment_info', sa.JSON(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.Enum('MONTHLY', 'ANNUAL', name='planid'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('process_tasks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('image_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('result_image_id', sa.String(length=50), nullable=True),
    sa.Column('output_size', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('edge_smoothing', sa.Boolean(), nullable=True),
    sa.Column('scene_type', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['result_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_tasks_id'), 'process_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_process_tasks_user_id'), 'process_tasks', ['user_id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('processed_image_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processed_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_user_id'), 'works', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_user_id'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_process_tasks_user_id'), table_name='process_tasks')
    op.drop_index(op.f('ix_process_tasks_id'), table_name='process_tasks')
    op.drop_table('process_tasks')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_images_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_verification_codes_phone_number'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###

