"""Remove all relationships

Revision ID: 81f57208e323
Revises: 4779c4b3a4f4
Create Date: 2026-01-01 00:44:44.550730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f57208e323'
down_revision = '4779c4b3a4f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

